# Generated by Django 5.1.1 on 2024-09-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='data_ano',
        ),
    ]
