# Generated by Django 5.1.1 on 2024-09-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_artigo_data_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='data_ultima_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
